### PR TITLE
Revert edgegrid change

### PR DESCRIPTION
**Pull request by bmatthew**
There are some unexpected build failures showing up -- to mitigate this I am reverting the edgegrid change I made last week, and can re-evaluate after we have better safety set up on our master branch

### CODE REVIEW

**Comment by swathimr** [comment]
can this still go in ben ? https://github.com/akamai/cli-edgeworkers/pull/47/files

**Comment by swathimr** [comment]
Also synk is showing some security test has failed.  was that the update we are reverting ?

**Comment by bmatthew** [comment]
> can this still go in ben ? https://github.com/akamai/cli-edgeworkers/pull/47/files

I've reverted this as well until we can verify the e2e tests pass.

> Also synk is showing some security test has failed. was that the update we are reverting ?

Yeah it's complaining because I'm putting it back on a flagged dependency.

**Comment by swathimr** [comment]
LGTM

**Pull request merged**
